services:
  fastagi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastagi:latest
    restart: always
    container_name: fastagi
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - FASTAGI_HOST=${FASTAGI_HOST:-0.0.0.0}
      - FASTAGI_PORT=${FASTAGI_PORT:-4753}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
    ports:
      - "4753:4753"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      start_period: 2s
      timeout: 5s
      retries: 3

networks:
  default: 
    driver: bridge
    name: agiserver_network


